export enum ROUTES {
    HOMEPAGE = '/',
    DEVELOPERS = '/developer',
    ABOUTUS = '/aboutus',
    ECOSYSTEM = '/ecosystem',
    SOLUTIONS = '/solutions',
    DISCORD = 'https://discord.gg/AvailProject',
    GITHUB = 'https://github.com/availproject',
    TWITTER = 'https://twitter.com/AvailProject',
    LINKEDIN = 'https://www.linkedin.com/company/availproject/',
    DOCUMENTATION = 'https://availproject.github.io/',
    TYPES_OF_NODES = '/da/operate-a-node/node-types',
    API_DOCS = 'https://availproject.github.io/using-avail/communicating-with-avail',
    VALIDATOR = 'https://availproject.github.io/join-the-network/run-avail/validator-node-setup',
    BECOME_VALIDATOR = '/da/operate-a-node/become-a-validator',
    FAUCET = 'https://availproject.github.io/using-avail/getting-started/testnet-faucet',
    EXPLORER = 'https://availproject.github.io/using-avail/getting-started/avail-explorer',
    CAREERS = 'https://avail.keka.com/careers',
    CLIENT_SETUP = 'https://availproject.github.io/join-the-network/run-avail/light-client-setup',
    COMMUNITY = 'https://discord.gg/AvailProject',
    BLOG = 'https://blog.availproject.org/',
    NETWORK = 'https://availproject.github.io/join-the-network/networks',
    REFER_DOCS = 'https://github.com/availproject/data-availability/blob/93c547ce4efce3e992b573179a8d22b3657fdcee/reference%20document/Avail%20Reference%20Paper%20v2.1%206%20Nov%202024.pdf',
    WORKING = 'https://availproject.github.io/join-the-network/node-types#validator-nodes',
    HOWITWORKS='https://blog.availproject.org/the-data-availability-problem/'
}
