name: Spell Checking
on:
  pull_request:
    paths:
      - '**/*.md'

jobs:
  spell-check:
    name: Check Spelling
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Check spelling
      uses: check-spelling/check-spelling@v0.0.19
